/* Product catalog – shared data */
const PRODUCTS = {
  p01: {
    id: 'p01', cat: 'brush', price: 4990,
    image: 'image/product-01.png',
    name_th: 'Chanel Makeup Brush Set',
    name_en: 'Chanel Makeup Brush Set',
    desc_th: 'ชุดแปรงแต่งหน้าพรีเมียม พร้อมกระเป๋าผ้ากำมะหยี่หรูหรา ขนแปรงนุ่ม เกลี่ยง่าย เหมาะสำหรับงานแต่งหน้ามืออาชีพและใช้ประจำวัน',
    desc_en: 'Premium makeup brush set with luxurious velvet pouch. Soft bristles for seamless blending — ideal for pro and everyday use.',
    badge: 'พรีเมียม',
    details_th: [
      'ชุดแปรงคุณภาพพรีเมียม',
      'กระเป๋าผ้ากำมะหยี่พร้อมสายรัด',
      'ขนแปรงสังเคราะห์นุ่ม ไม่บาดผิว',
      'เหมาะกับรองพื้น แป้ง และคอนทัวร์'
    ],
    details_en: [
      'Premium quality brush set',
      'Velvet pouch with strap',
      'Soft synthetic bristles',
      'For foundation, powder & contour'
    ]
  },
  p02: {
    id: 'p02', cat: 'brush', price: 590,
    image: 'image/product-02.jpg',
    name_th: 'Pink Makeup Brush Set',
    name_en: 'Pink Makeup Brush Set',
    desc_th: 'ชุดแปรงแต่งหน้าสีชมพู 7 ชิ้น พร้อมกระเป๋าซิปพกพาสะดวก ครบทั้งแปรงใหญ่และแปรงตา',
    desc_en: '7-piece pink brush set with zip case. Includes face and eye brushes for complete makeup.',
    badge: 'ขายดี',
    details_th: ['7 ชิ้นครบชุด', 'กระเป๋าซิปพกพา', 'ด้ามจับสีชมพูสวย', 'เหมาะกับมือใหม่'],
    details_en: ['7-piece complete set', 'Portable zip case', 'Pink handles', 'Beginner friendly']
  },
  p03: {
    id: 'p03', cat: 'brush', price: 790,
    image: 'image/product-03.jpg',
    name_th: 'Konvy Soft Brush Set',
    name_en: 'Konvy Soft Brush Set',
    desc_th: 'ชุดแปรงแต่งหน้าโทนชมพูนู้ด นุ่มนวล พร้อมซองหนังสวยหรู ให้ลุคดูแพง',
    desc_en: 'Soft nude-pink brushes with elegant leather case. Luxury look and feel.',
    badge: null,
    details_th: ['โทนชมพูนู้ด', 'ซองหนังหรู', 'ขนแปรงนุ่มพิเศษ', 'หลายขนาดในชุด'],
    details_en: ['Nude-pink tone', 'Leather case', 'Extra soft bristles', 'Multiple sizes']
  },
  p04: {
    id: 'p04', cat: 'eyeliner', price: 199,
    image: 'image/product-04.png',
    name_th: 'Lock & Wing Hyper Stay Eyeliner',
    name_en: 'Lock & Wing Hyper Stay Eyeliner',
    desc_th: 'อายไลเนอร์หัวพู่กัน ติดทนนาน สีดำสนิท กันน้ำ เขียนง่าย ไม่เลอะ',
    desc_en: 'Long-wear waterproof liquid eyeliner with brush tip. Deep black, smudge-proof.',
    badge: 'ใหม่',
    details_th: ['หัวพู่กันคมชัด', 'กันน้ำ กันเหงื่อ', 'สีดำสนิท', 'ติดทนทั้งวัน'],
    details_en: ['Fine brush tip', 'Waterproof', 'Deep black', 'All-day wear']
  },
  p05: {
    id: 'p05', cat: 'eyeliner', price: 159,
    image: 'image/product-05.jpg',
    name_th: 'Cathy Doll Cute Press Gel Eyeliner',
    name_en: 'Cathy Doll Cute Press Gel Eyeliner',
    desc_th: 'เจลอายไลเนอร์เนื้อเนียน กันน้ำ มาพร้อมปลายสปันจ์เบลนด์ สำหรับลุคสโมกกี้',
    desc_en: 'Waterproof gel eyeliner with blend sponge tip for soft smoky looks.',
    badge: null,
    details_th: ['เนื้อเจลเนียน', 'ปลายสปันจ์เบลนด์', 'กันน้ำ', 'เขียนและเบลนด์ได้'],
    details_en: ['Smooth gel formula', 'Blend sponge tip', 'Waterproof', 'Line & blend']
  },
  p06: {
    id: 'p06', cat: 'eyeliner', price: 890,
    image: 'image/product-06.jpg',
    name_th: 'HERA Liquid Eyeliner',
    name_en: 'HERA Liquid Eyeliner',
    desc_th: 'อายไลเนอร์เหลวหัวพู่กันคมชัด จากเกาหลี ติดทนทั้งวัน ไม่เลอะง่าย',
    desc_en: 'Korean liquid eyeliner with precise brush tip. Long-lasting, smudge-resistant.',
    badge: 'แนะนำ',
    details_th: ['แบรนด์เกาหลี HERA', 'หัวพู่กันคม', 'ติดทนนาน', 'สีดำเข้ม'],
    details_en: ['Korean brand HERA', 'Precise tip', 'Long-lasting', 'Intense black']
  },
  p07: {
    id: 'p07', cat: 'foundation', price: 245,
    image: 'image/product-07.jpg',
    name_th: 'Maybelline Fit Me Matte + Poreless',
    name_en: 'Maybelline Fit Me Matte + Poreless',
    desc_th: 'รองพื้นเนื้อแมท คุมมัน ปกปิดรูขุมขน SPF22 โทน 120 เหมาะกับผิวมัน–ผสม',
    desc_en: 'Matte foundation that controls oil and blurs pores. SPF22 shade 120.',
    badge: 'ขายดี',
    details_th: ['เนื้อแมทคุมมัน', 'ปกปิดรูขุมขน', 'SPF22', 'โทน 120'],
    details_en: ['Matte oil-control', 'Pore-blurring', 'SPF22', 'Shade 120']
  },
  p08: {
    id: 'p08', cat: 'foundation', price: 299,
    image: 'image/product-08.jpg',
    name_th: 'Beauty Infinity Double Lasting Foundation',
    name_en: 'Beauty Infinity Double Lasting Foundation',
    desc_th: 'รองพื้นปกปิดแน่น ติดทนนาน เนื้อเนียนเรียบ ให้ผิวดูสมบูรณ์แบบ',
    desc_en: 'Full-coverage long-lasting foundation with smooth, even finish.',
    badge: null,
    details_th: ['ปกปิดสูง', 'ติดทนนาน', 'เนื้อเนียน', 'ไม่เป็นคราบง่าย'],
    details_en: ['High coverage', 'Long wear', 'Smooth texture', 'Less caking']
  },
  p09: {
    id: 'p09', cat: 'foundation', price: 329,
    image: 'image/product-09.jpg',
    name_th: 'Maybelline Super Stay Lumi-Matte',
    name_en: 'Maybelline Super Stay Lumi-Matte',
    desc_th: 'รองพื้นติดทนสูงสุด 30 ชม. เนื้อลูมิ-แมท SPF16 โทน 115 ให้ผิวโกลว์แบบแมท',
    desc_en: 'Up to 30-hour wear lumi-matte foundation. SPF16 shade 115.',
    badge: null,
    details_th: ['ติดทนสูงสุด 30 ชม.', 'เนื้อ Lumi-Matte', 'SPF16', 'โทน 115'],
    details_en: ['Up to 30H wear', 'Lumi-Matte finish', 'SPF16', 'Shade 115']
  },
  p10: {
    id: 'p10', cat: 'blush', price: 199,
    image: 'image/product-10.jpg',
    name_th: 'LA GLACE Baebie Vibes – Hot Pink',
    name_en: 'LA GLACE Baebie Vibes – Hot Pink',
    desc_th: 'บลัชออนเนื้อซาติน สีชมพูสดใส ให้ลุคสดใสมีชีวิตชีวา เกลี่ยง่าย',
    desc_en: 'Satin hot pink blush for a fresh, vibrant look. Easy to blend.',
    badge: 'ใหม่',
    details_th: ['เนื้อซาติน', 'สีชมพูสด', 'เกลี่ยง่าย', 'ตลับใสสวย'],
    details_en: ['Satin finish', 'Hot pink', 'Blendable', 'Clear compact']
  },
  p11: {
    id: 'p11', cat: 'blush', price: 199,
    image: 'image/product-11.jpg',
    name_th: 'LA GLACE Baebie Vibes – Black',
    name_en: 'LA GLACE Baebie Vibes – Black',
    desc_th: 'บลัช/ไฮไลท์โทนดำเงา สำหรับลุคสโมกกี้และแต่งหน้าพิเศษ',
    desc_en: 'Black shimmer blush/highlighter for smoky and special looks.',
    badge: null,
    details_th: ['โทนดำเงา', 'ใช้เป็นไฮไลท์ได้', 'ลุคสโมกกี้', 'เม็ดสีแน่น'],
    details_en: ['Shimmery black', 'Can use as highlight', 'Smoky looks', 'Pigmented']
  },
  p12: {
    id: 'p12', cat: 'blush', price: 199,
    image: 'image/product-12.jpg',
    name_th: 'LA GLACE Baebie Vibes – Soft Pink',
    name_en: 'LA GLACE Baebie Vibes – Soft Pink',
    desc_th: 'บลัชออนสีชมพูนู้ดอ่อน เนื้อเนียน เกลี่ยง่าย เหมาะกับทุกโทนผิว',
    desc_en: 'Soft nude-pink blush. Smooth, blendable, suits all skin tones.',
    badge: null,
    details_th: ['ชมพูนู้ดอ่อน', 'เนื้อเนียน', 'เกลี่ยง่าย', 'ใช้ทุกวันได้'],
    details_en: ['Soft nude pink', 'Smooth texture', 'Easy blend', 'Everyday wear']
  },
  p13: {
    id: 'p13', cat: 'powder', price: 149,
    image: 'image/product-13.jpg',
    name_th: 'Bhaesaj Compact Powder',
    name_en: 'Bhaesaj Compact Powder',
    desc_th: 'แป้งพัฟคุมมัน เนื้อเนียน ปกปิดเรียบเนียน มีกระจกในตลับ พกพาสะดวก',
    desc_en: 'Oil-control compact powder with mirror. Smooth coverage, portable.',
    badge: null,
    details_th: ['คุมมันดี', 'มีกระจกในตลับ', 'เนื้อเนียน', 'ราคาคุ้ม'],
    details_en: ['Oil control', 'Built-in mirror', 'Smooth finish', 'Great value']
  },
  p14: {
    id: 'p14', cat: 'powder', price: 179,
    image: 'image/product-14.jpg',
    name_th: 'About U Compact Powder',
    name_en: 'About U Compact Powder',
    desc_th: 'แป้งพัฟเนื้อละเอียด คุมมันยาวนาน พร้อมกระจกในตลับ ให้ผิวแมทสวย',
    desc_en: 'Fine compact powder with long oil control and mirror. Matte finish.',
    badge: null,
    details_th: ['เนื้อละเอียด', 'คุมมันยาวนาน', 'มีกระจก', 'ผิวแมท'],
    details_en: ['Fine texture', 'Long oil control', 'With mirror', 'Matte finish']
  },
  p15: {
    id: 'p15', cat: 'powder', price: 349,
    image: 'image/product-15.jpg',
    name_th: 'Beauty Infinity Everyday Cushion SPF50',
    name_en: 'Beauty Infinity Everyday Cushion SPF50',
    desc_th: 'คุชชั่นปกปิดเนียนกริบ กันแดด SPF50 PA+++ ใช้ได้ทุกวัน เนื้อบางเบา',
    desc_en: 'Everyday cushion with SPF50 PA+++. Light coverage, natural finish.',
    badge: 'แนะนำ',
    details_th: ['SPF50 PA+++', 'ปกปิดเนียน', 'เนื้อบางเบา', 'ใช้ประจำวัน'],
    details_en: ['SPF50 PA+++', 'Natural coverage', 'Lightweight', 'Daily use']
  },
  p16: {
    id: 'p16', cat: 'lipstick', price: 189,
    image: 'image/product-16.jpg',
    name_th: 'Giffarine Lipstick – Magenta',
    name_en: 'Giffarine Lipstick – Magenta',
    desc_th: 'ลิปสติกสีม่วงอมชมพู เนื้อครีมมี่ เม็ดสีแน่น ติดทน ให้ริมฝีปากดูอวบอิ่ม',
    desc_en: 'Creamy magenta lipstick. Pigmented, long-wear, full-looking lips.',
    badge: null,
    details_th: ['สีม่วงอมชมพู', 'เนื้อครีมมี่', 'เม็ดสีแน่น', 'แบรนด์ Giffarine'],
    details_en: ['Magenta shade', 'Creamy texture', 'High pigment', 'Giffarine']
  },
  p17: {
    id: 'p17', cat: 'lipstick', price: 169,
    image: 'image/product-17.jpg',
    name_th: 'Classic Red Lipstick',
    name_en: 'Classic Red Lipstick',
    desc_th: 'ลิปสติกสีแดงคลาสสิก เนื้อเนียนนุ่ม ให้ลุคหรูหราและมั่นใจ',
    desc_en: 'Classic red creamy lipstick for an elegant, confident look.',
    badge: 'ขายดี',
    details_th: ['สีแดงคลาสสิก', 'เนื้อเนียนนุ่ม', 'ลุคหรูหรา', 'ใช้ได้หลายโอกาส'],
    details_en: ['Classic red', 'Creamy soft', 'Elegant look', 'Versatile']
  },
  p18: {
    id: 'p18', cat: 'lipstick', price: 169,
    image: 'image/product-18.jpg',
    name_th: 'Hot Pink Lipstick',
    name_en: 'Hot Pink Lipstick',
    desc_th: 'ลิปสติกสีชมพูสด เนื้อครีม เม็ดสีชัด ติดทนนาน สดใสมีชีวิตชีวา',
    desc_en: 'Bright hot pink creamy lipstick. Bold color, long-lasting.',
    badge: null,
    details_th: ['สีชมพูสด', 'เนื้อครีม', 'เม็ดสีชัด', 'ติดทน'],
    details_en: ['Hot pink', 'Creamy', 'Bold pigment', 'Long wear']
  },
  p19: {
    id: 'p19', cat: 'lipstick', price: 189,
    image: 'image/product-19.jpg',
    name_th: 'Giffarine Lipstick – Nude',
    name_en: 'Giffarine Lipstick – Nude',
    desc_th: 'ลิปสติกโทนนู้ดน้ำตาล เนื้อเนียน เหมาะกับทุกโทนผิว ลุคสุภาพธรรมชาติ',
    desc_en: 'Nude-brown lipstick for all skin tones. Natural, polished look.',
    badge: null,
    details_th: ['โทนนู้ดน้ำตาล', 'เหมาะทุกโทนผิว', 'เนื้อเนียน', 'ลุคธรรมชาติ'],
    details_en: ['Nude brown', 'All skin tones', 'Smooth', 'Natural look']
  },
  p20: {
    id: 'p20', cat: 'lipstick', price: 1890,
    image: 'image/product-20.jpg',
    name_th: 'Dior Lip Glow Oil – Coral',
    name_en: 'Dior Lip Glow Oil – Coral',
    desc_th: 'ลิปออยล์เนื้อเงาวาว สีคอรัลมีชิมเมอร์ บำรุงริมฝีปากให้อิ่มน้ำ',
    desc_en: 'Shimmering coral lip oil for glossy, nourished lips.',
    badge: 'พรีเมียม',
    details_th: ['แบรนด์ Dior', 'เนื้อออยล์เงา', 'สีคอรัลชิมเมอร์', 'บำรุงริมฝีปาก'],
    details_en: ['Dior', 'Glossy oil texture', 'Coral shimmer', 'Nourishing']
  },
  p21: {
    id: 'p21', cat: 'lipstick', price: 1890,
    image: 'image/product-21.jpg',
    name_th: 'Dior Lip Glow Oil – Soft Pink',
    name_en: 'Dior Lip Glow Oil – Soft Pink',
    desc_th: 'ลิปออยล์สีชมพูอ่อน เนื้อใสเงา ให้ลุคธรรมชาติ',
    desc_en: 'Sheer soft pink lip oil with natural glossy finish.',
    badge: 'พรีเมียม',
    details_th: ['สีชมพูอ่อน', 'เนื้อออยล์', 'ลุคธรรมชาติ', 'แบรนด์ Dior'],
    details_en: ['Soft pink', 'Oil texture', 'Natural look', 'Dior']
  },
  p22: {
    id: 'p22', cat: 'lipstick', price: 1650,
    image: 'image/product-22.jpg',
    name_th: 'Dior Addict Lip Glow Balm',
    name_en: 'Dior Addict Lip Glow Balm',
    desc_th: 'ลิปบาล์มสีชมพูใส บำรุงและเพิ่มสีตาม pH ริมฝีปาก',
    desc_en: 'Color-reviving lip balm that adapts to your lips.',
    badge: null,
    details_th: ['ลิปบาล์ม', 'สีชมพูใส', 'บำรุงริมฝีปาก', 'Dior'],
    details_en: ['Lip balm', 'Sheer pink', 'Nourishing', 'Dior']
  },
  p23: {
    id: 'p23', cat: 'lipstick', price: 199,
    image: 'image/product-23.jpg',
    name_th: 'Gentle Matte Collagen Lipstick #03 Starfish',
    name_en: 'Gentle Matte Collagen Lipstick #03 Starfish',
    desc_th: 'ลิปแมทเนื้อนุ่ม มีคอลลาเจน สีชมพูคอรัล #03 Starfish',
    desc_en: 'Soft matte collagen lipstick in coral pink #03 Starfish.',
    badge: 'ขายดี',
    details_th: ['เนื้อแมทนุ่ม', 'ผสมคอลลาเจน', 'สี #03 Starfish', 'ราคาคุ้ม'],
    details_en: ['Soft matte', 'With collagen', 'Shade #03', 'Great value']
  },
  p24: {
    id: 'p24', cat: 'lipstick', price: 1290,
    image: 'image/product-24.jpg',
    name_th: 'Shiseido Lipstick – Soft Rose',
    name_en: 'Shiseido Lipstick – Soft Rose',
    desc_th: 'ลิปสติกชิเซโด้ สีชมพูโรส เนื้อเนียน ติดทน',
    desc_en: 'Shiseido soft rose lipstick with smooth long wear.',
    badge: null,
    details_th: ['แบรนด์ Shiseido', 'สี Soft Rose', 'เนื้อเนียน', 'ติดทน'],
    details_en: ['Shiseido', 'Soft rose', 'Smooth', 'Long wear']
  },
  p25: {
    id: 'p25', cat: 'lipstick', price: 329,
    image: 'image/product-25.jpg',
    name_th: 'Maybelline Superstay Teddy Tint – Pink',
    name_en: 'Maybelline Superstay Teddy Tint – Pink',
    desc_th: 'ลิปทินท์เนื้อแมทนุ่ม สีชมพูตุ่น ติดทนสไตล์ Superstay',
    desc_en: 'Soft matte teddy tint in muted pink, long-lasting.',
    badge: 'ใหม่',
    details_th: ['เนื้อทินท์แมท', 'สีชมพูตุ่น', 'ติดทนนาน', 'Maybelline'],
    details_en: ['Matte tint', 'Muted pink', 'Long wear', 'Maybelline']
  },
  p26: {
    id: 'p26', cat: 'lipstick', price: 199,
    image: 'image/product-26.png',
    name_th: 'Gentle Matte Collagen Lipstick #10 Lobster',
    name_en: 'Gentle Matte Collagen Lipstick #10 Lobster',
    desc_th: 'ลิปแมทคอลลาเจน สีนู้ดน้ำตาลอมส้ม #10 Lobster',
    desc_en: 'Matte collagen lipstick in nude-brown #10 Lobster.',
    badge: null,
    details_th: ['#10 Lobster', 'เนื้อแมท', 'คอลลาเจน', 'โทนนู้ด'],
    details_en: ['#10 Lobster', 'Matte', 'Collagen', 'Nude tone']
  },
  p27: {
    id: 'p27', cat: 'lipstick', price: 329,
    image: 'image/product-27.jpg',
    name_th: 'Maybelline Superstay Teddy Tint – Coral',
    name_en: 'Maybelline Superstay Teddy Tint – Coral',
    desc_th: 'ลิปทินท์แมทสีคอรัลอุ่น ติดทน นุ่มริมฝีปาก',
    desc_en: 'Warm coral soft-matte teddy tint, long-lasting.',
    badge: null,
    details_th: ['สีคอรัล', 'เนื้อทินท์นุ่ม', 'ติดทน', 'Maybelline'],
    details_en: ['Coral shade', 'Soft tint', 'Long wear', 'Maybelline']
  },
  p28: {
    id: 'p28', cat: 'lipstick', price: 149,
    image: 'image/product-28.jpg',
    name_th: 'Hya Tinted Lip Balm Set',
    name_en: 'Hya Tinted Lip Balm Set',
    desc_th: 'ลิปบาล์มทินท์ไฮยา มีหลายสี Peach / Watermelon / Apple บำรุงปาก',
    desc_en: 'Hya tinted lip balm multi-shade set for soft tinted lips.',
    badge: 'ขายดี',
    details_th: ['หลายสีในชุด', 'ผสม HYA', 'บำรุงปาก', 'ทาแล้วมีสี'],
    details_en: ['Multi shades', 'With HYA', 'Nourishing', 'Light tint']
  },
  p29: {
    id: 'p29', cat: 'lipstick', price: 1290,
    image: 'image/product-29.jpg',
    name_th: 'Shiseido Lipstick – Plum Shimmer',
    name_en: 'Shiseido Lipstick – Plum Shimmer',
    desc_th: 'ลิปสติกชิเซโด้ สีม่วงพลัมมีชิมเมอร์ ลุคหรูหรา',
    desc_en: 'Shiseido plum shimmer lipstick for an elegant look.',
    badge: null,
    details_th: ['สีพลัมชิมเมอร์', 'Shiseido', 'ลุคหรู', 'เนื้อเนียน'],
    details_en: ['Plum shimmer', 'Shiseido', 'Elegant', 'Smooth']
  },
  p30: {
    id: 'p30', cat: 'lipstick', price: 129,
    image: 'image/product-30.jpg',
    name_th: 'Hya Lip Balm – Rose',
    name_en: 'Hya Lip Balm – Rose',
    desc_th: 'ลิปบาล์มไฮยา สีโรส บำรุงปากนุ่ม ชุ่มชื้น ด้วย Vitamin E',
    desc_en: 'Rose Hya lip balm with Vitamin E for soft hydrated lips.',
    badge: null,
    details_th: ['สี Rose', 'Vitamin E', 'HYA', 'ปากนุ่มชุ่มชื้น'],
    details_en: ['Rose', 'Vitamin E', 'HYA', 'Hydrating']
  },
  p31: {
    id: 'p31', cat: 'blush', price: 1590,
    image: 'image/product-31.jpg',
    name_th: 'Bobbi Brown Pot Rouge – Coral',
    name_en: 'Bobbi Brown Pot Rouge – Coral',
    desc_th: 'บลัชครีมบ็อบบี้ บราวน์ โทนคอรัล เนื้อเนียนเกลี่ยง่าย',
    desc_en: 'Bobbi Brown cream pot rouge in coral, blendable.',
    badge: 'พรีเมียม',
    details_th: ['เนื้อครีม', 'สีคอรัล', 'Bobbi Brown', 'เกลี่ยง่าย'],
    details_en: ['Cream formula', 'Coral', 'Bobbi Brown', 'Blendable']
  },
  p32: {
    id: 'p32', cat: 'blush', price: 1590,
    image: 'image/product-32.jpg',
    name_th: 'Bobbi Brown Pot Rouge – Pink',
    name_en: 'Bobbi Brown Pot Rouge – Pink',
    desc_th: 'บลัชครีมโทนชมพู จาก Bobbi Brown ให้แก้มดูมีชีวิตชีวา',
    desc_en: 'Bobbi Brown cream blush in vibrant pink.',
    badge: 'พรีเมียม',
    details_th: ['เนื้อครีม', 'สีชมพู', 'Bobbi Brown', 'แก้มสดใส'],
    details_en: ['Cream', 'Pink', 'Bobbi Brown', 'Fresh cheeks']
  },
  p33: {
    id: 'p33', cat: 'blush', price: 690,
    image: 'image/product-33.jpg',
    name_th: 'The Body Shop Blush Palette',
    name_en: 'The Body Shop Blush Palette',
    desc_th: 'พาเลทบลัช 3 โทน ชมพู-พีช เกลี่ยได้หลายลุค',
    desc_en: '3-tone blush palette in pink-peach shades.',
    badge: null,
    details_th: ['3 โทนสี', 'ชมพู-พีช', 'The Body Shop', 'คุ้มค่า'],
    details_en: ['3 tones', 'Pink-peach', 'The Body Shop', 'Value']
  },
  p34: {
    id: 'p34', cat: 'blush', price: 2100,
    image: 'image/product-34.jpg',
    name_th: 'Dior Rouge Blush – Soft Pink',
    name_en: 'Dior Rouge Blush – Soft Pink',
    desc_th: 'บลัชดิออร์ สีชมพูอ่อนมีชิมเมอร์ พร้อมแปรงในตลับ',
    desc_en: 'Dior soft pink shimmer blush with built-in brush.',
    badge: 'พรีเมียม',
    details_th: ['Dior', 'ชิมเมอร์ชมพู', 'มีแปรงในตลับ', 'ลุคหรู'],
    details_en: ['Dior', 'Pink shimmer', 'Built-in brush', 'Luxury']
  },
  p35: {
    id: 'p35', cat: 'blush', price: 299,
    image: 'image/product-35.jpg',
    name_th: 'KMA Dual Blush – Purple & Magenta',
    name_en: 'KMA Dual Blush – Purple & Magenta',
    desc_th: 'บลัชคู่ KMA โทนม่วงและมาเจนต้า ลุคสดใส',
    desc_en: 'KMA dual blush in purple and magenta.',
    badge: 'ใหม่',
    details_th: ['2 สีในตลับ', 'ม่วง + มาเจนต้า', 'KMA', 'ลุคสด'],
    details_en: ['2 shades', 'Purple + magenta', 'KMA', 'Vibrant']
  },
  p36: {
    id: 'p36', cat: 'blush', price: 159,
    image: 'image/product-36.jpg',
    name_th: 'Soft Round Blush – Coral Pink',
    name_en: 'Soft Round Blush – Coral Pink',
    desc_th: 'บลัชออนตลับกลม สีชมพูคอรัล เนื้อเนียนเกลี่ยง่าย',
    desc_en: 'Round compact coral-pink blush, easy to blend.',
    badge: null,
    details_th: ['ตลับกลม', 'สีคอรัลชมพู', 'เกลี่ยง่าย', 'ใช้ประจำวัน'],
    details_en: ['Round compact', 'Coral pink', 'Blendable', 'Everyday']
  },
  p37: {
    id: 'p37', cat: 'blush', price: 249,
    image: 'image/product-37.jpg',
    name_th: 'KMA Blush Bomb Cheek Color',
    name_en: 'KMA Blush Bomb Cheek Color',
    desc_th: 'บลัชบอมบ์ KMA สีคอรัลอุ่น เนื้อแน่นเม็ดสีชัด',
    desc_en: 'KMA Blush Bomb in warm coral, highly pigmented.',
    badge: 'ขายดี',
    details_th: ['Blush Bomb', 'สีคอรัล', 'เม็ดสีชัด', 'KMA'],
    details_en: ['Blush Bomb', 'Coral', 'Pigmented', 'KMA']
  },
  p38: {
    id: 'p38', cat: 'blush', price: 159,
    image: 'image/product-38.jpg',
    name_th: 'Soft Round Blush – Nude Peach',
    name_en: 'Soft Round Blush – Nude Peach',
    desc_th: 'บลัชออนโทนพีชนู้ด ตลับกลม ลุคธรรมชาติ',
    desc_en: 'Nude peach round blush for a natural flush.',
    badge: null,
    details_th: ['โทนพีชนู้ด', 'ลุคธรรมชาติ', 'เกลี่ยง่าย', 'ใช้ทุกวัน'],
    details_en: ['Nude peach', 'Natural', 'Blendable', 'Daily']
  },
  p39: {
    id: 'p39', cat: 'blush', price: 189,
    image: 'image/product-39.jpg',
    name_th: 'Lovely Cookie Blusher – Coral',
    name_en: 'Lovely Cookie Blusher – Coral',
    desc_th: 'บลัชคุ๊กกี้ สีคอรัลสด พร้อมพัฟขนนุ่มในชุด',
    desc_en: 'Cookie blusher in bright coral with soft puff.',
    badge: null,
    details_th: ['สีคอรัลสด', 'มีพัฟในชุด', 'เนื้อเนียน', 'น่ารัก'],
    details_en: ['Bright coral', 'With puff', 'Smooth', 'Cute']
  },
  p40: {
    id: 'p40', cat: 'powder', price: 199,
    image: 'image/product-40.jpg',
    name_th: 'Classic Compact Powder – Beige',
    name_en: 'Classic Compact Powder – Beige',
    desc_th: 'แป้งพัฟโทนเบจ คุมมัน มีกระจกในตลับ',
    desc_en: 'Beige oil-control compact powder with mirror.',
    badge: null,
    details_th: ['โทนเบจ', 'คุมมัน', 'มีกระจก', 'พกพาง่าย'],
    details_en: ['Beige', 'Oil control', 'Mirror', 'Portable']
  },
  p41: {
    id: 'p41', cat: 'powder', price: 890,
    image: 'image/product-41.jpg',
    name_th: 'Kanebo Pressed Powder – Translucent',
    name_en: 'Kanebo Pressed Powder – Translucent',
    desc_th: 'แป้งคัทซีลโปร่งแสง Kanebo เนื้อบางเบา คุมมัน',
    desc_en: 'Kanebo translucent pressed powder, lightweight oil control.',
    badge: 'แนะนำ',
    details_th: ['โปร่งแสง', 'Kanebo', 'เนื้อบางเบา', 'คุมมัน'],
    details_en: ['Translucent', 'Kanebo', 'Lightweight', 'Oil control']
  },
  p42: {
    id: 'p42', cat: 'powder', price: 299,
    image: 'image/product-42.jpg',
    name_th: 'Sivanna Super Cover Foundation Powder SPF30',
    name_en: 'Sivanna Super Cover Foundation Powder SPF30',
    desc_th: 'แป้งผสมรองพื้น Sivanna ปกปิด คุมมัน SPF30 PA+++',
    desc_en: 'Sivanna foundation powder SPF30 PA+++, full coverage.',
    badge: 'ขายดี',
    details_th: ['ผสมรองพื้น', 'SPF30 PA+++', 'ปกปิดดี', 'Sivanna'],
    details_en: ['Foundation powder', 'SPF30 PA+++', 'Coverage', 'Sivanna']
  },
  p43: {
    id: 'p43', cat: 'powder', price: 279,
    image: 'image/product-43.png',
    name_th: 'Sivanna Super Cover Two Way Cake NO.02',
    name_en: 'Sivanna Super Cover Two Way Cake NO.02',
    desc_th: 'แป้งทูเวย์เค้ก Sivanna เบอร์ 02 ปกปิดเนียน',
    desc_en: 'Sivanna two-way cake shade 02, smooth coverage.',
    badge: null,
    details_th: ['NO.02', 'ทูเวย์เค้ก', 'ปกปิดเนียน', 'Sivanna'],
    details_en: ['NO.02', 'Two-way cake', 'Smooth', 'Sivanna']
  },
  p44: {
    id: 'p44', cat: 'powder', price: 149,
    image: 'image/product-44.jpg',
    name_th: 'Bhaesaj Compact Powder – Natural',
    name_en: 'Bhaesaj Compact Powder – Natural',
    desc_th: 'แป้งพัฟเภสัช โทนธรรมชาติ คุมมัน ราคาคุ้ม',
    desc_en: 'Bhaesaj natural tone compact, oil control, great value.',
    badge: null,
    details_th: ['โทนธรรมชาติ', 'คุมมัน', 'เภสัช', 'คุ้มราคา'],
    details_en: ['Natural tone', 'Oil control', 'Bhaesaj', 'Value']
  },
  p45: {
    id: 'p45', cat: 'powder', price: 890,
    image: 'image/product-45.jpg',
    name_th: 'Kanebo Pressed Powder No.01',
    name_en: 'Kanebo Pressed Powder No.01',
    desc_th: 'แป้งคัทซีล Kanebo เบอร์ 01 โปร่งใส คุมมัน 24 ชม.',
    desc_en: 'Kanebo No.01 translucent powder, 24h oil control.',
    badge: 'แนะนำ',
    details_th: ['No.01 โปร่งใส', 'คุมมัน 24 ชม.', 'เนื้อบางเบา', 'Kanebo'],
    details_en: ['No.01 clear', '24h oil control', 'Sheer', 'Kanebo']
  },
  p46: {
    id: 'p46', cat: 'eyebrow', price: 199,
    image: 'image/product-46.jpg',
    name_th: 'Browit Pro Makeup Flat Eyebrow Pencil 2IN1',
    name_en: 'Browit Pro Makeup Flat Eyebrow Pencil 2IN1',
    desc_th: 'ดินสอเขียนคิ้วหัวแบน 2IN1 มีแปรงปัดคิ้ว สี Sandstone Brown',
    desc_en: 'Flat 2-in-1 brow pencil with brush, Sandstone Brown.',
    badge: 'ขายดี',
    details_th: ['หัวแบน 2IN1', 'มีแปรง', 'Browit', 'เขียนง่าย'],
    details_en: ['Flat tip 2IN1', 'With brush', 'Browit', 'Easy draw']
  },
  p47: {
    id: 'p47', cat: 'eyebrow', price: 249,
    image: 'image/product-47.jpg',
    name_th: 'Browit Ultra Fine Duo Brow Pencil & Mascara',
    name_en: 'Browit Ultra Fine Duo Brow Pencil & Mascara',
    desc_th: 'ดินสอคิ้วหัวเล็กพิเศษ + มาสคาร่าคิ้ว ติดทน 24 ชม.',
    desc_en: 'Ultra-fine brow pencil duo with mascara, 24h wear.',
    badge: 'ใหม่',
    details_th: ['หัวเล็กพิเศษ', 'มาสคาร่าคิ้ว', '24 ชม.', 'Browit'],
    details_en: ['Ultra fine', 'Brow mascara', '24h', 'Browit']
  },
  p48: {
    id: 'p48', cat: 'eyebrow', price: 179,
    image: 'image/product-48.jpg',
    name_th: 'beWiLD Perfectionist Eyebrow #03 Mocha',
    name_en: 'beWiLD Perfectionist Eyebrow #03 Mocha',
    desc_th: 'ดินสอเขียนคิ้ว beWiLD สี Mocha คิ้วปัง สั่งได้ กันน้ำ',
    desc_en: 'beWiLD brow pencil #03 Mocha, waterproof, natural look.',
    badge: null,
    details_th: ['#03 Mocha', 'กันน้ำ', 'คิ้วปัง', 'beWiLD'],
    details_en: ['#03 Mocha', 'Waterproof', 'Defined', 'beWiLD']
  },
  p49: {
    id: 'p49', cat: 'eyebrow', price: 179,
    image: 'image/product-49.jpg',
    name_th: 'beWiLD Perfectionist Eyebrow Pencil 2IN1',
    name_en: 'beWiLD Perfectionist Eyebrow Pencil 2IN1',
    desc_th: 'ดินสอคิ้ว 2IN1 หัวดินสอ + แปรง กันน้ำ กันเหงื่อ',
    desc_en: '2-in-1 brow pencil with spoolie, water and sweat resistant.',
    badge: null,
    details_th: ['2IN1', 'กันน้ำกันเหงื่อ', 'เขียนง่าย', 'beWiLD'],
    details_en: ['2IN1', 'Water resistant', 'Easy', 'beWiLD']
  },
  p50: {
    id: 'p50', cat: 'eyebrow', price: 259,
    image: 'image/product-50.jpg',
    name_th: 'Kathy 3B Brow Superstar',
    name_en: 'Kathy 3B Brow Superstar',
    desc_th: 'ดินสอเขียนคิ้ว 3 หัว Kathy ดินสอ + มาสคาร่า + หัวฟองน้ำ',
    desc_en: 'Kathy 3-in-1 brow: pencil, mascara and sponge tip.',
    badge: 'แนะนำ',
    details_th: ['3 หัวในแท่งเดียว', 'Kathy', 'เขียนคิ้วครบ', 'พกง่าย'],
    details_en: ['3-in-1', 'Kathy', 'Complete brow', 'Portable']
  },
  p51: {
    id: 'p51', cat: 'eyebrow', price: 159,
    image: 'image/product-51.jpg',
    name_th: 'USTAR Slim Brow & Liner 2IN1',
    name_en: 'USTAR Slim Brow & Liner 2IN1',
    desc_th: 'ดินสอคิ้วและอายไลเนอร์ 2IN1 หัวเรียว กันน้ำ',
    desc_en: '2-in-1 slim brow and liner, waterproof.',
    badge: null,
    details_th: ['2IN1 คิ้ว+ไลเนอร์', 'หัวเรียว', 'กันน้ำ', 'USTAR'],
    details_en: ['Brow + liner', 'Slim tip', 'Waterproof', 'USTAR']
  },
  p52: {
    id: 'p52', cat: 'eyebrow', price: 259,
    image: 'image/product-52.jpg',
    name_th: 'Kathy 3B Brow – Detail Pack',
    name_en: 'Kathy 3B Brow – Detail Pack',
    desc_th: 'Kathy 3B Brow ชุดละเอียด ดินสอคิ้วซุปตาร์ 3 ฟังก์ชัน',
    desc_en: 'Kathy 3B Brow detail set with triple brow functions.',
    badge: null,
    details_th: ['3 ฟังก์ชัน', 'Kathy 3B', 'เขียนคม', 'คุ้ม'],
    details_en: ['3 functions', 'Kathy 3B', 'Precise', 'Value']
  },
  p53: {
    id: 'p53', cat: 'eyebrow', price: 159,
    image: 'image/product-53.jpg',
    name_th: 'USTAR Slim Brow & Liner Natural Brown',
    name_en: 'USTAR Slim Brow & Liner Natural Brown',
    desc_th: 'USTAR Slim Brow สี Natural Brown คิ้วคม มาเป็นคู่ไลเนอร์',
    desc_en: 'USTAR slim brow in Natural Brown with liner tip.',
    badge: null,
    details_th: ['Natural Brown', '2IN1', 'กันน้ำ', 'USTAR'],
    details_en: ['Natural Brown', '2IN1', 'Waterproof', 'USTAR']
  },
  p54: {
    id: 'p54', cat: 'eyebrow', price: 390,
    image: 'image/product-54.png',
    name_th: 'KATE Tokyo Eyebrow Pencil Z – Black',
    name_en: 'KATE Tokyo Eyebrow Pencil Z – Black',
    desc_th: 'ดินสอเขียนคิ้ว KATE หัวเล็กพิเศษ สีดำ เขียนเส้นขนคิ้วได้ละเอียด',
    desc_en: 'KATE ultra-fine black brow pencil for hair-like strokes.',
    badge: null,
    details_th: ['หัวเล็กพิเศษ', 'สีดำ', 'KATE Tokyo', 'เส้นคม'],
    details_en: ['Ultra fine', 'Black', 'KATE Tokyo', 'Precise']
  },
  p55: {
    id: 'p55', cat: 'eyeliner', price: 249,
    image: 'image/product-55.jpg',
    name_th: 'Browit Forever Pro Eyeliner – Deep Black',
    name_en: 'Browit Forever Pro Eyeliner – Deep Black',
    desc_th: 'อายไลเนอร์หัวสักหลาด 0.1 มม. สีดำสนิท กันน้ำ แห้งเร็ว',
    desc_en: '0.1mm felt-tip eyeliner deep black, waterproof, quick-dry.',
    badge: 'ขายดี',
    details_th: ['หัว 0.1 มม.', 'Deep Black', 'กันน้ำ', 'Browit'],
    details_en: ['0.1mm tip', 'Deep Black', 'Waterproof', 'Browit']
  },
  p56: {
    id: 'p56', cat: 'eyebrow', price: 390,
    image: 'image/product-56.png',
    name_th: 'KATE Tokyo Eyebrow Pencil Z – Light Brown',
    name_en: 'KATE Tokyo Eyebrow Pencil Z – Light Brown',
    desc_th: 'ดินสอคิ้ว KATE สีน้ำตาลอ่อน หัวเล็ก เขียนเส้นธรรมชาติ',
    desc_en: 'KATE light brown ultra-fine brow pencil.',
    badge: null,
    details_th: ['Light Brown', 'หัวเล็ก', 'KATE', 'ธรรมชาติ'],
    details_en: ['Light Brown', 'Fine tip', 'KATE', 'Natural']
  },
  p57: {
    id: 'p57', cat: 'eyeliner', price: 415,
    image: 'image/product-57.jpg',
    name_th: 'beneficial Proliner Eyeliner',
    name_en: 'beneficial Proliner Eyeliner',
    desc_th: 'อายไลเนอร์เนื้อลิควิด สีดำสนิท ขนแปรงเรียว Made in Japan',
    desc_en: 'Liquid black eyeliner with fine brush, made in Japan.',
    badge: null,
    details_th: ['เนื้อลิควิด', 'Made in Japan', 'สีดำสนิท', 'beneficial'],
    details_en: ['Liquid', 'Made in Japan', 'Deep black', 'beneficial']
  },
  p58: {
    id: 'p58', cat: 'eyeliner', price: 249,
    image: 'image/product-58.jpg',
    name_th: 'Browit Forever Pro Eyeliner Soft Felt Tip',
    name_en: 'Browit Forever Pro Eyeliner Soft Felt Tip',
    desc_th: 'อายไลเนอร์หัวสักหลาดนุ่ม เส้นคม กันน้ำ จากญี่ปุ่น',
    desc_en: 'Soft felt-tip waterproof eyeliner with Japanese ink.',
    badge: null,
    details_th: ['หัวสักหลาดนุ่ม', 'กันน้ำ', 'แห้งเร็ว', 'Browit'],
    details_en: ['Soft felt tip', 'Waterproof', 'Quick dry', 'Browit']
  },
  p59: {
    id: 'p59', cat: 'eyebrow', price: 390,
    image: 'image/product-59.png',
    name_th: 'KATE Eyebrow Pencil Z BR-1',
    name_en: 'KATE Eyebrow Pencil Z BR-1',
    desc_th: 'ดินสอคิ้ว KATE เบอร์ BR-1 น้ำตาลอ่อน เขียนเส้นขนคิ้ว',
    desc_en: 'KATE BR-1 light brown hair-stroke brow pencil.',
    badge: null,
    details_th: ['BR-1', 'น้ำตาลอ่อน', 'KATE', 'เส้นละเอียด'],
    details_en: ['BR-1', 'Light brown', 'KATE', 'Fine lines']
  },
  p60: {
    id: 'p60', cat: 'eyeliner', price: 415,
    image: 'image/product-60.jpg',
    name_th: 'beneficial Proliner – Soft Brush',
    name_en: 'beneficial Proliner – Soft Brush',
    desc_th: 'อายไลเนอร์ beneficial หัวแปรงนุ่ม เขียนหางตาคม',
    desc_en: 'beneficial soft-brush eyeliner for sharp wing lines.',
    badge: null,
    details_th: ['หัวแปรงนุ่ม', 'สีดำ', 'ญี่ปุ่น', 'beneficial'],
    details_en: ['Soft brush', 'Black', 'Japan', 'beneficial']
  },
  p61: {
    id: 'p61', cat: 'eyeliner', price: 129,
    image: 'image/product-61.jpg',
    name_th: 'Mistine Super Black Eyeliner',
    name_en: 'Mistine Super Black Eyeliner',
    desc_th: 'อายไลเนอร์มิสทีน สีดำเข้ม เขียนง่าย ราคาคุ้ม',
    desc_en: 'Mistine super black eyeliner, easy application.',
    badge: 'ขายดี',
    details_th: ['สีดำเข้ม', 'Mistine', 'เขียนง่าย', 'คุ้มราคา'],
    details_en: ['Deep black', 'Mistine', 'Easy', 'Value']
  },
  p62: {
    id: 'p62', cat: 'eyeliner', price: 399,
    image: 'image/product-62.jpg',
    name_th: 'beneficial Liquid Eyeliner Pen',
    name_en: 'beneficial Liquid Eyeliner Pen',
    desc_th: 'อายไลเนอร์ปากกา beneficial หัวพู่กันคม สีดำสนิท',
    desc_en: 'beneficial liquid pen eyeliner with precise brush tip.',
    badge: null,
    details_th: ['หัวพู่กันคม', 'สีดำสนิท', 'beneficial', 'ติดทน'],
    details_en: ['Brush tip', 'Deep black', 'beneficial', 'Long wear']
  },
  p63: {
    id: 'p63', cat: 'eyeliner', price: 249,
    image: 'image/product-63.png',
    name_th: 'Browit Forever Pro Eyeliner – Deep Brown',
    name_en: 'Browit Forever Pro Eyeliner – Deep Brown',
    desc_th: 'อายไลเนอร์ Browit สีน้ำตาลเข้ม หัว 0.1 มม. กันน้ำ',
    desc_en: 'Browit deep brown 0.1mm felt-tip waterproof eyeliner.',
    badge: null,
    details_th: ['Deep Brown', '0.1 มม.', 'กันน้ำ', 'Browit'],
    details_en: ['Deep Brown', '0.1mm', 'Waterproof', 'Browit']
  },
  p64: {
    id: 'p64', cat: 'eyeliner', price: 199,
    image: 'image/product-64.jpg',
    name_th: "Merrez'ca Super Black Long-Lasting Eyeliner",
    name_en: "Merrez'ca Super Black Long-Lasting Eyeliner",
    desc_th: 'อายไลเนอร์ Merrez\'ca สีดำเข้ม ติดทน กันน้ำ กันเหงื่อ',
    desc_en: "Merrez'ca super black long-lasting waterproof eyeliner.",
    badge: 'แนะนำ',
    details_th: ['สีดำเข้ม', 'ติดทนนาน', 'กันน้ำ', "Merrez'ca"],
    details_en: ['Super black', 'Long-lasting', 'Waterproof', "Merrez'ca"]
  }

};

const CAT_LABELS = {
  brush: { th: 'แปรงแต่งหน้า', en: 'Brushes' },
  eyeliner: { th: 'อายไลเนอร์', en: 'Eyeliner' },
  foundation: { th: 'รองพื้น', en: 'Foundation' },
  blush: { th: 'บลัชออน', en: 'Blush' },
  powder: { th: 'แป้ง & คุชชั่น', en: 'Powder & Cushion' },
  lipstick: { th: 'ลิปสติก', en: 'Lipstick' },
  eyebrow: { th: 'เขียนคิ้ว', en: 'Eyebrow' }
};
